name: 'Check Syntax Action'
description: 'Lint and check YAML files and GitHub Actions syntax'
author: Evgenii Kuzakov
inputs:
  yamllint_version:
    description: 'yamllint version'
    required: false
    default: "1.32.0"
  actionlint_version:
    description: 'actionlint version'
    required: false
    default: "1.6.25"
  yamllint_config:
    description: 'yamllint config'
    required: false
    default: ".github/yamllint.yaml"
  actionlint_config:
    description: 'actionlint config'
    required: false
    default: ".github/actionlint.yaml"

runs:
  using: 'composite'
  steps:
    - name: Debugs outputs
      run: |
        echo "yamllint_version: ${{ inputs.yamllint_version }}"
        echo "actionlint_version: ${{ inputs.actionlint_version }}"
        env
        find / -name yamllint.yaml 2>/dev/null
      shell: bash
    - name: Cache pip data
      id: cache_pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-data-${{ runner.os }}-yamllint-${{ inputs.yamllint_version }}
        restore-keys: pip-data-${{ runner.os }}-yamllint-${{ inputs.yamllint_version }}

    - name: Cache actionlint
      id: cache_actionlint
      uses: actions/cache@v2
      with:
        path: ~/.local/bin/actionlint
        key: actionlint-${{ inputs.actionlint_version }}

    - name: Install yamllint
      if: steps.cache_pip.outputs.cache-hit != 'true'
      run: pip install yamllint==${{ inputs.yamllint_version }}
      shell: bash

    - name: Install actionlint
      if: steps.cache_actionlint.outputs.cache-hit != 'true'
      run: |
        mkdir -p "${HOME}/.local/bin"
        curl -sSLf https://github.com/rhysd/actionlint/releases/download/v${{ inputs.actionlint_version }}/actionlint_${{ inputs.actionlint_version }}_linux_amd64.tar.gz | tar xzv -C "${HOME}/.local/bin/"
      shell: bash

    - name: Check YAML Syntax for All Files
      run: |
        find . -name "*.yml" -o -name "*.yaml" | while read -r file; do
          yamllint -c "${{ inputs.yamllint_config }}" "$file"
        done
      shell: bash

    - name: Check GitHub Actions Workflow Syntax
      run: actionlint -c "${{ inputs.actionlint_config }}"
      shell: bash
